
import { Product } from './types';

export const COLORS = {
  BRAND_OLIVE: '#8ca67a',
  BRAND_DARK: '#000000',
  BRAND_LIGHT: '#ffffff',
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'k1',
    shopifyId: 'gid://shopify/Product/1',
    handle: 'signature-silk-evening-drape',
    name: 'Signature Silk Evening Drape',
    price: 680,
    description: 'A masterpiece of fluid silk, designed to move with the body. Features a hand-rolled hem and bias-cut silhouette.',
    category: 'Women',
    image: 'https://images.unsplash.com/photo-1539109132314-34a9c668e007?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k5', 'k8', 'k9', 'z1'],
    composition: '100% Mulberry Silk',
    origin: 'Lyon, France',
    shippingTier: 'Klyora Express (5-7 Days)'
  },
  {
    id: 'z1',
    shopifyId: 'gid://shopify/Product/z1',
    handle: 'zen-celestial-slip-dress',
    name: 'Celestial Silk Slip',
    price: 450,
    description: 'A Zendrop-sourced exclusive, refined by the Klyora atelier. Minimalist silhouette with adjustable straps and a cowl neck.',
    category: 'Women',
    image: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k1', 'z3'],
    composition: 'Silk Blend Satin',
    origin: 'Global Atelier',
    shippingTier: 'Global Express (7 Days)'
  },
  {
    id: 'z6',
    shopifyId: 'gid://shopify/Product/z6',
    handle: 'velvet-nocturne-gown',
    name: 'Velvet Nocturne Gown',
    price: 1800,
    description: 'A deep midnight velvet masterpiece. Architectural corset boning and a dramatic side slit for evening galas.',
    category: 'Exclusive',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k9', 'k4'],
    composition: 'Italian Cotton Velvet',
    origin: 'Milan Atelier',
    shippingTier: 'Secured White Glove',
    inventoryStatus: 'Limited Edition'
  },
  {
    id: 'z2',
    shopifyId: 'gid://shopify/Product/z2',
    handle: 'zen-urban-nomad-knit',
    name: 'Urban Nomad Oversized Knit',
    price: 280,
    description: 'Chunky, textured knit with an editorial fit. Sourced for the modern wanderer who values both warmth and architectural style.',
    category: 'Seasonal',
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k7', 'z4'],
    composition: 'Organic Cotton / Recycled Wool',
    origin: 'Ethical Global Studio',
    shippingTier: 'Standard Express (8-10 Days)'
  },
  {
    id: 'k2',
    shopifyId: 'gid://shopify/Product/2',
    handle: 'heritage-cashmere-overcoat',
    name: 'Heritage Cashmere Overcoat',
    price: 1250,
    description: 'Crafted from 100% Mongolian cashmere. A timeless staple featuring a structured shoulder and relaxed waist.',
    category: 'Men',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k3', 'k7', 'k10', 'z7'],
    composition: '100% Grade-A Cashmere',
    origin: 'Inner Mongolia / Biella, Italy',
    shippingTier: 'White Glove Concierge'
  },
  {
    id: 'z7',
    shopifyId: 'gid://shopify/Product/z7',
    handle: 'onyx-peak-tuxedo',
    name: 'Onyx Peak Tuxedo',
    price: 2100,
    description: 'The pinnacle of menswear. Sourced via Zen-Exclusive channels and tailored to architectural perfection.',
    category: 'Exclusive',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k2', 'k4'],
    composition: 'Super 150s Wool / Silk Facings',
    origin: 'London Atelier',
    shippingTier: 'White Glove Concierge'
  },
  {
    id: 'z3',
    shopifyId: 'gid://shopify/Product/z3',
    handle: 'zen-minimalist-structured-tote',
    name: 'Atelier Minimalist Tote',
    price: 320,
    description: 'Vegan leather tote with sharp, architectural lines. A Zendrop bestseller customized for the Klyora collection.',
    category: 'Exclusive',
    image: 'https://images.unsplash.com/photo-1544816153-199d82175e1e?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k5', 'z1'],
    composition: 'Premium Vegan Leather',
    origin: 'Global Studio',
    shippingTier: 'Global Express (7 Days)'
  },
  {
    id: 'k9',
    shopifyId: 'gid://shopify/Product/9',
    handle: 'ethereal-tulle-ball-gown',
    name: 'Ethereal Tulle Ball Gown',
    price: 2400,
    description: 'A dramatic, floor-length gown with hand-applied sequins and layered Italian tulle. Designed for the most exclusive galas.',
    category: 'Exclusive',
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k1', 'k4', 'z6'],
    composition: 'Nylon Tulle / Silk Lining',
    origin: 'Milan, Italy',
    inventoryStatus: 'Limited Edition',
    shippingTier: 'Secured White Glove'
  },
  {
    id: 'z4',
    shopifyId: 'gid://shopify/Product/z4',
    handle: 'zen-parisian-velvet-mini',
    name: 'Parisian Night Velvet Mini',
    price: 380,
    description: 'Deep black velvet with a subtle sheen. A versatile piece for the Klyora night collection, sourced through the Zendrop network.',
    category: 'Women',
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k11', 'z2'],
    composition: 'Cotton Velvet Blend',
    origin: 'Europe Studio',
    shippingTier: 'Global Express (7 Days)'
  },
  {
    id: 'k3',
    shopifyId: 'gid://shopify/Product/3',
    handle: 'tailored-wool-pleated-trouser',
    name: 'Tailored Wool Pleated Trouser',
    price: 320,
    description: 'High-waisted silhouette with sharp architectural pleats. Italian virgin wool blend.',
    category: 'Men',
    image: 'https://images.unsplash.com/photo-1594932224828-b4b057bfe4ee?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k2', 'k6', 'k12'],
    composition: '98% Virgin Wool, 2% Elastane',
    origin: 'Tuscany, Italy'
  },
  {
    id: 'z5',
    shopifyId: 'gid://shopify/Product/z5',
    handle: 'zen-architectural-linen-shorts',
    name: 'Architectural Linen Shorts',
    price: 190,
    description: 'Structured linen shorts with a refined waistline. Perfect for seasonal resort wear, sourced via Zendrop fulfillment.',
    category: 'Seasonal',
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k12', 'z2'],
    composition: '100% European Linen',
    origin: 'Resort Atelier',
    shippingTier: 'Global Express (7 Days)'
  },
  {
    id: 'k11',
    shopifyId: 'gid://shopify/Product/11',
    handle: 'plisse-pleated-midi-dress',
    name: 'Plissé Pleated Midi Dress',
    price: 520,
    description: 'Architectural pleating that creates a dynamic silhouette. Shimmering fabric that catches the light with every step.',
    category: 'Women',
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k8', 'k5', 'z4'],
    composition: 'Recycled Poly-Satin',
    origin: 'Tokyo, Japan'
  },
  {
    id: 'k4',
    shopifyId: 'gid://shopify/Product/4',
    handle: 'sculpted-velvet-gala-blazer',
    name: 'Sculpted Velvet Gala Blazer',
    price: 950,
    description: 'Deep midnight velvet with silk-satin lapels. Engineered for a perfect evening silhouette.',
    category: 'Exclusive',
    image: 'https://images.unsplash.com/photo-1555069519-03ef8088825d?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k6', 'k9', 'z7'],
    composition: 'Cotton Velvet / Silk Satin Trims',
    origin: 'Paris, France'
  },
  {
    id: 'k10',
    shopifyId: 'gid://shopify/Product/10',
    handle: 'toscana-shearling-aviator',
    name: 'Toscana Shearling Aviator',
    price: 1850,
    description: 'Ultra-warm shearling jacket with a rugged leather exterior. Hand-finished seams and heavy-duty hardware.',
    category: 'Seasonal',
    image: 'https://images.unsplash.com/photo-1520975661595-6453be3f7070?q=80&w=1000&auto=format&fit=crop',
    relatedIds: ['k2', 'k7'],
    composition: '100% Toscana Sheepskin',
    origin: 'Madrid, Spain'
  }
];
